CREATE TABLE `atividade_short` (
  `cdcontrole` int(11) NOT NULL AUTO_INCREMENT,
  `cdatividade` int(11) NOT NULL,
  `dstitulo` varchar(100) NOT NULL,
  `dtlimite` date NOT NULL,
  `dtfatal` date DEFAULT NULL,
  `cdprocesso` int(11) DEFAULT NULL,
  `nrcnj` varchar(50) DEFAULT NULL,
  `nrpasta` varchar(100) DEFAULT NULL,
  `nrprocesso` varchar(100) DEFAULT NULL,
  `partes` varchar(400) DEFAULT NULL,
  `grupo` varchar(100) DEFAULT NULL,
  `subgrupo` varchar(100) DEFAULT NULL,
  `responsaveis` varchar(2000) NOT NULL,
  `interessados` varchar(3000) DEFAULT NULL,
  `cdusuario` int(11) NOT NULL,
  `cdstatus` int(11) NOT NULL,
  `cdusuario_interessado` int(11) DEFAULT NULL,
  `tpatividade` varchar(1) NOT NULL,
  `dtregistro` date DEFAULT NULL,
  `dtconcluido` date DEFAULT NULL,
  `status` varchar(50) DEFAULT NULL,
  `cdgrupo` int(11) DEFAULT NULL,
  PRIMARY KEY (`cdcontrole`),
  KEY `fk_ativ_ativ_short` (`cdatividade`),
  KEY `atividade_short_cdusuario_IDX` (`cdusuario`) USING BTREE,
  KEY `atividade_short_cdusuario_interessado_IDX` (`cdusuario_interessado`) USING BTREE,
  KEY `atividade_short_dtlimite_IDX` (`dtlimite`) USING BTREE,
  CONSTRAINT `fk_ativ_ativ_short` FOREIGN KEY (`cdatividade`) REFERENCES `atividade` (`cdatividade`)
) ENGINE=InnoDB AUTO_INCREMENT=25012 DEFAULT CHARSET=latin1;
